### ISSUE TITLE
Server Logs: Page::OverflowError

### ISSUE THREAD

**Issue by MartinHinz** [xronos-ch/xronos.rails#199]
In production.log, there are many:

```
I, [2023-02-04T23:35:23.733230 #121]  INFO -- : [1d961bd5-abcf-48f3-b465-a5f1e6e67ef6] Completed 500 Internal Server Error in 1401ms (ActiveRecord: 1335.0ms | Allocations: 1282083)
F, [2023-02-04T23:35:23.733840 #121] FATAL -- : [1d961bd5-abcf-48f3-b465-a5f1e6e67ef6]   
[1d961bd5-abcf-48f3-b465-a5f1e6e67ef6] Pagy::OverflowError (expected :page in 1..17510; got 41044):
[1d961bd5-abcf-48f3-b465-a5f1e6e67ef6]   
[1d961bd5-abcf-48f3-b465-a5f1e6e67ef6] app/controllers/data_controller.rb:20:in `block (2 levels) in index'
[1d961bd5-abcf-48f3-b465-a5f1e6e67ef6] app/controllers/data_controller.rb:18:in `index'
```

**Comment by joeroe** [comment]
I'm fairly sure there are no incoming links to these pages. The IP making these requests is yet another shady-looking SEO crawler.

Technically I suppose asking for a page outside the range should give a 404 error instead of 500, but I don't think it's worth us monkey-patching Pagy for that edge case.
