### ISSUE TITLE
Rails 7 version crashes in production

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#306]
E.g.:

```
2023-09-19T12:35:47.248565532Z /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:43:in `expand_path': no implicit conversion of Propshaft::Assembly into String (TypeError)
2023-09-19T12:35:47.248575912Z 	from /usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:43:in `initialize'
2023-09-19T12:35:47.248579028Z 	from /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:216:in `new'
2023-09-19T12:35:47.248581522Z 	from /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:216:in `build_manifest'
2023-09-19T12:35:47.248583947Z 	from /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:229:in `block in <class:Railtie>'
2023-09-19T12:35:47.248586552Z 	from /usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'
2023-09-19T12:35:47.248597783Z 	from /usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
2023-09-19T12:35:47.248608473Z 	from /usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
2023-09-19T12:35:47.248611068Z 	from /usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'
2023-09-19T12:35:47.248613512Z 	from /usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:75:in `each'
2023-09-19T12:35:47.248615867Z 	from /usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'
2023-09-19T12:35:47.248618231Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/application/finisher.rb:87:in `block in <module:Finisher>'
2023-09-19T12:35:47.248620726Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
2023-09-19T12:35:47.248623070Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
2023-09-19T12:35:47.248625415Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
2023-09-19T12:35:47.248627809Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
2023-09-19T12:35:47.248630093Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2023-09-19T12:35:47.248632498Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
2023-09-19T12:35:47.248634802Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
2023-09-19T12:35:47.248637127Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
2023-09-19T12:35:47.248639952Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
2023-09-19T12:35:47.248642256Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
2023-09-19T12:35:47.248644601Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
2023-09-19T12:35:47.248646855Z 	from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
2023-09-19T12:35:47.248649099Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
2023-09-19T12:35:47.248651484Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
2023-09-19T12:35:47.248653828Z 	from /application/config/environment.rb:5:in `<top (required)>'
2023-09-19T12:35:47.248656222Z 	from config.ru:3:in `require_relative'
2023-09-19T12:35:47.248658477Z 	from config.ru:3:in `block in <main>'
2023-09-19T12:35:47.248660841Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'
2023-09-19T12:35:47.248663185Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'
2023-09-19T12:35:47.248665510Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'
2023-09-19T12:35:47.248667814Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'
2023-09-19T12:35:47.248673124Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2023-09-19T12:35:47.248675499Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:249:in `app'
2023-09-19T12:35:47.248677773Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:422:in `wrapped_app'
2023-09-19T12:35:47.248680097Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:312:in `block in start'
2023-09-19T12:35:47.248682402Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:379:in `handle_profiling'
2023-09-19T12:35:47.248684706Z 	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:311:in `start'
2023-09-19T12:35:47.248687010Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:38:in `start'
2023-09-19T12:35:47.248689375Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:143:in `block in perform'
2023-09-19T12:35:47.248691779Z 	from <internal:kernel>:90:in `tap'
2023-09-19T12:35:47.248694184Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/commands/server/server_command.rb:134:in `perform'
2023-09-19T12:35:47.248696518Z 	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
2023-09-19T12:35:47.248698792Z 	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
2023-09-19T12:35:47.248701097Z 	from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
2023-09-19T12:35:47.248703621Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
2023-09-19T12:35:47.248705956Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
2023-09-19T12:35:47.248708260Z 	from /usr/local/bundle/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<top (required)>'
2023-09-19T12:35:47.248710695Z 	from bin/rails:4:in `require'
2023-09-19T12:35:47.248712949Z 	from bin/rails:4:in `<main>'
```

**Comment by joeroe** [comment]
Solved in 880c6438b0fe3c945f1257941ad9b3ac05b5c916
