### ISSUE TITLE
Data Download results in error

### ISSUE THREAD

**Issue by MartinHinz** [xronos-ch/xronos.rails#5]
Go to initial data table, select all, press download. Result:

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

In Logfile:

```
I, [2019-09-09T12:09:43.065515 #56]  INFO -- : [2c965cf7-e67b-45f1-9178-fec878ffaf6c] Completed 500 Internal Server Error in 1395ms (ActiveRecord: 37.7ms)
F, [2019-09-09T12:09:43.066107 #56] FATAL -- : [2c965cf7-e67b-45f1-9178-fec878ffaf6c]   
F, [2019-09-09T12:09:43.066233 #56] FATAL -- : [2c965cf7-e67b-45f1-9178-fec878ffaf6c] NoMethodError (undefined method `bp' for #<Measurement:0x00007fd8a59e3448>):
F, [2019-09-09T12:09:43.066271 #56] FATAL -- : [2c965cf7-e67b-45f1-9178-fec878ffaf6c]   
F, [2019-09-09T12:09:43.066311 #56] FATAL -- : [2c965cf7-e67b-45f1-9178-fec878ffaf6c] app/models/measurement.rb:43:in `block (2 levels) in to_csv'
[2c965cf7-e67b-45f1-9178-fec878ffaf6c] app/models/measurement.rb:41:in `block in to_csv'
[2c965cf7-e67b-45f1-9178-fec878ffaf6c] app/models/measurement.rb:17:in `to_csv'
[2c965cf7-e67b-45f1-9178-fec878ffaf6c] app/controllers/data_controller.rb:228:in `block (2 levels) in index'
[2c965cf7-e67b-45f1-9178-fec878ffaf6c] app/controllers/data_controller.rb:211:in `index'

```

**Comment by MartinHinz** [comment]
Solved with current production release. Sorry, Clemens ;-)
