### ISSUE TITLE
Sum Cal image download results in Error

### ISSUE THREAD

**Issue by MartinHinz** [xronos-ch/xronos.rails#6]
Go to initial data table, select all, press sum calibrate, press 'export to raster...', select png.

Result:

```
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.
```

In Log File:

```
[[FI, [2019-09-09T12:12:55.006689 #56]  INFO -- : [0ccf3c20-4895-4533-96fb-8ff1b846d406] Started POST "/c14_measurements/export_chart?authenticity_token=IpUnzQ1cL6wtJbwE%2F7t5DnTNVW%2BeTqk49uvH93cnK5iSmmeGjzjIh46hoc5wRrdGFHCwlIZC8Z6xl70F92RXSw%3D%3D" for 130.92.173.40 at 2019-09-09 12:12:55 +0000
F, [2019-09-09T12:12:55.007553 #56] FATAL -- : [0ccf3c20-4895-4533-96fb-8ff1b846d406]   
F, [2019-09-09T12:12:55.007607 #56] FATAL -- : [0ccf3c20-4895-4533-96fb-8ff1b846d406] ActionController::RoutingError (No route matches [POST] "/c14_measurements/export_chart"):
F, [2019-09-09T12:12:55.007659 #56] FATAL -- : [0ccf3c20-4895-4533-96fb-8ff1b846d406]   
F, [2019-09-09T12:12:55.007759 #56] FATAL -- : [0ccf3c20-4895-4533-96fb-8ff1b846d406] actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] rack (2.0.7) lib/rack/method_override.rb:22:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] rack (2.0.7) lib/rack/runtime.rb:22:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] railties (5.2.3) lib/rails/engine.rb:524:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] puma (3.12.1) lib/puma/configuration.rb:227:in `call'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] puma (3.12.1) lib/puma/server.rb:474:in `process_client'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] puma (3.12.1) lib/puma/server.rb:334:in `block in run'
[0ccf3c20-4895-4533-96fb-8ff1b846d406] puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'

```

**Comment by MartinHinz** [comment]
Solved with current production release
