### ISSUE TITLE
Bad data filters can cause a server error

### ISSUE THREAD

**Issue by joeroe** [xronos-ch/xronos.rails#86]
Steps to reproduce:

1. Open https://xronos.ch/map or https://xronos.ch/table
2. Open the data filters and type some garbage into "Lab Number"
3. Click "filter dates"

There is then an alert:

> DataTables warning: table id=selected_measurements-datatable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

And the user is prevented from navigating back to https://xronos.ch/map or https://xronos.ch/table because it triggers a 500 error in rails:

```
I, [2022-03-30T13:53:18.735702 #84]  INFO -- : [6e9a5596-efe0-454a-ac1e-65c1bca45514] Started GET "/table" for 130.92.173.67 at 2022-03-30 13:53:18 +0000
I, [2022-03-30T13:53:18.736482 #84]  INFO -- : [6e9a5596-efe0-454a-ac1e-65c1bca45514] Processing by DataController#index as HTML
I, [2022-03-30T13:53:18.739747 #84]  INFO -- : [6e9a5596-efe0-454a-ac1e-65c1bca45514] Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.3ms | Allocations: 988)
F, [2022-03-30T13:53:18.740749 #84] FATAL -- : [6e9a5596-efe0-454a-ac1e-65c1bca45514]   
[6e9a5596-efe0-454a-ac1e-65c1bca45514] NoMethodError (undefined method `split' for nil:NilClass):
[6e9a5596-efe0-454a-ac1e-65c1bca45514]   
[6e9a5596-efe0-454a-ac1e-65c1bca45514] app/controllers/data_controller.rb:256:in `get_data'
[6e9a5596-efe0-454a-ac1e-65c1bca45514] app/controllers/data_controller.rb:40:in `index'
```

This can break these views for the user until their session expires! See #87 

(For testing, you can get out of this situation by running `rake db:sessions:clear`).

**Comment by joeroe** [comment]
Fixed with the removal of datatables #105
